{{- if .Values.licenseKey }}
apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "newrelic.labels" . | indent 4 }}
  name: {{ template "newrelic.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  license: {{ .Values.licenseKey | b64enc }}
{{- end }}
