{{- if .Values.global.licenseKey }}
apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "newrelic.labels" . | indent 4 }}
  name: {{ template "newrelic.fullname" . }}-config
type: Opaque
data:
  license: {{ .Values.global.licenseKey | b64enc }}
{{- end }}
